Repository AvocadoUrlShortening/Backend, pull requests merged in 2024-01, with the labels that each got.

#3 feat: docker로 app과 mysql 연결
  Avocado/Dockerfile
  Avocado/build.gradle
  Avocado/docker-compose.yml
  Avocado/gradlew
  Avocado/src/main/resources/application.properties
Labels: Type: Feature

#10 인프라 세팅 및 CI/CD
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Avocado/.gitignore
  Avocado/Dockerfile
  Avocado/build.gradle
  Avocado/gradlew
  Avocado/src/main/java/url/shortener/Avocado/global/config/PropertyConfig.java
  Avocado/src/main/java/url/shortener/Avocado/global/config/RedisConfig.java
  Avocado/src/main/resources/application.properties
Labels: For: CI/CD, Status: Completed, Type: Configuration, Type: Feature

#12 Feature/issue 005 회원가입 로그인 구현
  .github/workflows/CI.yml
  Avocado/.gitignore
  Avocado/build.gradle
  Avocado/src/main/java/url/shortener/Avocado/AvocadoApplication.java
  Avocado/src/main/java/url/shortener/Avocado/domain/member/entity/AuthProvider.java
  Avocado/src/main/java/url/shortener/Avocado/domain/member/entity/Member.java
  Avocado/src/main/java/url/shortener/Avocado/domain/member/repository/MemberRepository.java
  Avocado/src/main/java/url/shortener/Avocado/global/config/AppConfig.java
  Avocado/src/main/java/url/shortener/Avocado/global/config/PropertyConfig.java
  Avocado/src/main/java/url/shortener/Avocado/global/config/RedisConfig.java
  Avocado/src/main/java/url/shortener/Avocado/infra/mail/application/EmailService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/annotation/AuthUser.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/api/AuthController.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/application/AuthService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/application/GoogleAuthService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/application/LocalAuthService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/application/NaverAuthService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/application/TokenService.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/config/SecurityConfig.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/request/LoginRequestDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/ErrorResponseDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/GoogleInfo.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/GoogleResponseDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/NaverResponseDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/SignUpResponseDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/dto/response/TokenResponseDto.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/exception/AuthErrorCode.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/exception/AuthException.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/exception/GlobalExceptionHandler.java
  Avocado/src/main/java/url/shortener/Avocado/infra/security/util/AuthArgumentResolver.java
  Avocado/src/main/resources/application.properties
Labels: Fir: Fix, For: API, Status: In Progress, Type: Logic
